---
title: Schedule (`r date()`)
output:
  html_document:
    fig_height: 7
    toc: yes
  pdf_document: default
---

```{r setup, echo=F, results='hide', message=F}

library(tidyverse)
library(lubridate)
library(readxl)
#library(writexl)

derm = read_xlsx("0schedule.xlsx") %>% 
  mutate(date = ymd(date), # register date 
  lesion = as.character(lesion)) %>%
  arrange(CID, lesion, date) %>%
  group_by(CID, lesion) %>%
  filter(row_number() == ifelse(length(which.max(date)), which.max(date), n())) %>%
  ungroup()
  
derm.name = 
  derm %>% 
  distinct(CID, name) %>%
  group_by(CID) %>%
  filter(row_number() == 1) %>% # make unique name
  ungroup()

d = 
  derm %>% 
  group_by(CID) %>% 
  summarise(
    date_last = max(date, na.rm=T),
    lesion_last = lesion[which(date == max(date, na.rm=T))]) %>% 
  right_join(derm) %>%
  mutate(
    i        = interval(ymd(date),      ymd(today()-1            )) %/% months(1),
    i7       = interval(ymd(date),      ymd(today()-1 + weeks(1) )) %/% months(1),
    i30      = interval(ymd(date),      ymd(today()-1 + months(1))) %/% months(1),
    i_last   = interval(ymd(date_last), ymd(today()-1            )) %/% months(1),
    i7_last  = interval(ymd(date_last), ymd(today()-1 +  weeks(1))) %/% months(1),
    i30_last = interval(ymd(date_last), ymd(today()-1 + months(1))) %/% months(1)
  ) %>% 
  mutate(
    show0 = case_when(
      i_last < 1 ~ as.character(NA), 
      is.na(date) ~ paste0(lesion, " (",date,")"),
      i >= 6 ~ paste0(lesion, " (",date,")"),
      T ~ as.character(NA)),
    show7 = case_when(
      i7_last < 1 ~ as.character(NA), 
      is.na(date) ~ paste0(lesion, " (",date,")"),
      i7 >= 6 ~ paste0(lesion, " (",date,")"),
      T ~ as.character(NA)),
    show30 = case_when(
      i30_last < 1 ~ as.character(NA), 
      is.na(date) ~ paste0(lesion, " (",date,")"),
      i30 >= 6 ~ paste0(lesion, " (",date,")"),
      T ~ as.character(NA))
  )  %>%
  group_by(CID, date_last, lesion_last) %>% 
  summarise(lesions0 = paste(show0[!is.na(show0)], collapse="<br> "),
            lesions7 = paste(show7[!is.na(show7)], collapse="<br> "),
            lesions30 = paste(show30[!is.na(show30)], collapse="<br> ")
  ) %>%
  mutate(last = paste0(lesion_last, "(", date_last, ")")) %>%
  ungroup() %>%
  left_join(derm.name) %>%
  select(CID, name, last, lesions0, lesions7, lesions30) %>%
  set_names(c("Chart_Number", "Name", "Last", "Today", "Next_Week", "Next_Month")) 

d0 = d %>% filter(Today != "" | Next_Week != "" | Next_Month != "") 

```
```{r list, echo=F, message=F}
d0 %>% knitr::kable()
```
