#!/bin/sh

if [ ! $1 ]; then
    echo Please input subject ID!
else
    export SUBJECT_ID=$1
    qsub -N fs_$SUBJECT_ID \
	-o /Users/hon-manliu/freesurfer/qsub.log/$SUBJECT_ID.log \
	-v SUBJECT_ID=$SUBJECT_ID /Users/hon-manliu/bin/freesurfer.qsub
fi

